language: python
python:
- "3.8-dev"
install:
  - pip install requests
  - pip install -r requirements.txt
script:
  - python3 app.py
 after_success:
  # Generate coverage report in xml format
  - coverage xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
